config/routes.rb
Bloccit::Application.routes.draw do

  get 'about', to: 'welcome#about'

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: [:show, :index]

  resources :topics do
    resources :posts, except: [:index], controller: 'topics/posts' do
      resources :favorites, only: [:create, :destroy]
      get '/up-vote', to: 'votes#up_vote', as: :up_vote
      get '/down-vote', to: 'votes#down_vote', as: :down_vote
    end
  end

  resource :dashboard, only: [:show]

  authenticated :user do
    root to: 'dashboards#show' 
  end

  root to: 'welcome#index'
 
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  include Paginate
  attr_accessible :description, :name, :public
  has_many :posts, dependent: :destroy

  default_scope order('created_at DESC')

  scope :visible_to, lambda { |user| user ? scoped : where(public: true) }

end

app/controllers/topics/posts_controller.rb
class Topics::PostsController < ApplicationController
  
  before_filter :ensure_post, except: [:new, :create]
  before_filter :ensure_topic
  before_filter :authenticate_user!
  after_filter :update_view_count, only: [:show]

  def show
    authorize! :read, @topic, message: 'You need to be signed in to do that'
    @comment = current_user.comments.build
    @comments = @post.comments
  end

  def new
    @post = Post.new
    authorize! :create, Post, message: 'You need to be a member to create a post'
  end

  def create
    @post = current_user.posts.build(params[:post])
    @post.topic = @topic
    authorize! :create, @post, message: 'You need to be signed up to do that'
    if @post.save_with_initial_vote
      redirect_to [@topic, @post], notice: 'Post saved'
    else
      render :new, alert: 'There was an error saving your post.  Please try again.'
    end
  end

  def edit
    render
    authorize! :edit, @post, message: 'You need to own the post to edit it'
  end

  def update
    authorize! :update, @post, message: 'You ned to own the post to edit it'
    if @post.update_attributes(params[:post])
      redirect_to [@topic, @post], notice: 'Post updated'
    else
      render :edit, alert: 'Post not updated; try again'
    end
  end

  def destroy
    title = @post.title
    authorize! :destroy, @post, message: 'You need to own the post to delete it'
    if @post.destroy
      redirect_to @topic, notice: "\"#{title}\" was deleted successfully"
    else
      render :show, error: 'There was an error deleting the post'
    end
  end

  private

  def update_view_count
    @post.increment_view_count
  end

  def ensure_post
    redirect_to topics_path, alert: 'No such post' unless post
  end

  def post
    @post ||= Post.find_by_id(params[:id])
  end

  def ensure_topic
    redirect_to topics_path, alert: 'No such topic' unless topic
  end

  def topic
    @topic ||= Topic.find_by_id(params[:topic_id])
  end
  
  helper_method :post
  helper_method :topic
  
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :ensure_topic, only: [:show, :edit, :update, :destroy]

  def index
    #@topics = Topic.visible_to(current_user).paginate(page: params[:page], per_page: 5)
    @topics = Topic.paginate(page: params[:page], per_page: 10)
  end

  def new
    @topic = Topic.new
    authorize! :create, @topic, message: 'You must be admin to do that'
  end

  def create
    @topic =Topic.new(params[:topic])
    authorize! :create, @topic, message: 'You must be admin to do that'
    if @topic.save
      redirect_to @topic, notice: 'Topic created'
    else
      render :new, alert: 'Topic creation failed; please try again'
    end
  end

  def update
    authorize! :update, @topic, message: 'You need to own the topic to update it'
    if @topic.update_attributes(params[:topic])
      redirect_to @topic
    else
      flash[:error] = "Error saving topic. Please try again"
      render :edit
    end
  end

  def show
    @posts = @topic.posts.includes(:user).paginate(page: params[:page], per_page: 5)
  end

  def edit
    authorize! :update, @topic, message: 'You must be admin to do that'
  end

  def destroy
    name = @topic.name
    authorize! :destroy, @topic, message: 'You need to be admin to do that'
    if @topic.destroy
      # redirect_to topics_path, notice: "#{name} was deleted successfully"
      redirect_to topics_path, notice: "Topic was deleted successfully"
    else
      render :show, error: 'There was an error deleting this topic'
    end
  end
  

  private

  def ensure_topic
    redirect_to root_path, notice: 'No such topic' unless topic
  end

  def topic
    @topic ||= Topic.find_by_id(params[:id])
  end
  
  helper_method :topic
  
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.haml
= form_for @topic do |f|
  %div 
    = f.label :name
    %br/ 
    = f.text_field :name, class: 'medium-text-field'
  %div 
    = f.label :description
    %br/ 
    = f.text_area :description, size: '30x10', class: 'medium-text-box'
  %div 
    = f.label :public, class: 'checkbox' do
      = f.check_box :public
      Public topic
  %div
    = f.submit 'Save', class: 'medium radius secondary button'

app/views/topics/edit.html.haml
%h1 Edit Topic
.row
  .large-4.columns
    %p Guidelines for new topic:
    %ul 
      %li Make sure content is appropriate
      %li Blah blah blah
      %li Yakety smakety
      %li Etc, etc, etc.
  .large-8.columns
    = render 'form'
    = link_to 'Cancel', :back, class: 'medium radius alert button'
 

app/views/topics/index.html.haml
%h1 Topics
.row
  .large-8.columns
    - @topics.each do |topic|
      = div_for(topic) do
        = link_to topic.name, topic
        %small= topic.description
    /= foundation_paginate @topics
    = my_paginate(@topics)
  .large-4.columns
    - if can? :create, topic
      = link_to 'new topic', new_topic_path, class: 'medium radius button'

app/views/topics/new.html.haml
%h1 New topic
.row
  .large-4.columns
    %p Guidelines for new topic
    %ul 
      %li Make sure content is appropriate
      %li Blah blah blah
      %li Yakety smakety
      %li Etc, etc, etc.
  .large-8.columns
    = render 'form'

app/views/topics/show.html.haml
= link_to 'Return to topics...', topics_path
%h2= "#{@topic.name.titleize}"
%br/ 
- if can? :update, @topic
  = link_to 'Edit topic', edit_topic_path, class: 'small radius button'
- if can? :destroy, @topic
  = link_to 'Delete topic', @topic, method: :delete, class: 'small radius alert button', confirm: 'Are you sure you want to delete this topic?'
.row
  .small-8.columns
    = div_for(@topic, class: 'topic') do
      %h3= @topic.name
      /%p= "Added by #{@topic.user.username}"
      %p= @topic.description
    - if @posts.any?
      %h3 Posts on this topic
      - @posts.each do |post|
        = div_for(post) do
          %h3= link_to(markdown(post.title), [@topic, post])
          %p
            = show_user_avatar(post.user, '80x80')
            updated
            = time_ago_in_words(post.created_at)
            ago by
            = post.username
            %br/ 
            = post.comments.count
            comments
            = render partial: 'votes/voter', locals: { topic: @topic, post: post }

          %p
            = show_post_image(post)
            = markdown post.body
          - if can? :edit, post
            = link_to 'Edit post', edit_post_path(post), class: 'small radius button'
      /= foundation_paginate @posts
      = my_paginate @posts
  - if can? :create, Post
    = link_to 'New Post', new_topic_post_path(@topic), class: 'medium radius button'
 