config/routes.rb
Bloccit::Application.routes.draw do

  get 'about', to: 'welcome#about'

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: [:show, :index]

  resources :topics do
    resources :posts, except: [:index], controller: 'topics/posts' do
      resources :favorites, only: [:create, :destroy]
      get '/up-vote', to: 'votes#up_vote', as: :up_vote
      get '/down-vote', to: 'votes#down_vote', as: :down_vote
    end
  end

  resource :dashboard, only: [:show]

  authenticated :user do
    root to: 'dashboards#show' 
  end

  root to: 'welcome#index'
 
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Paginate
  attr_accessible :body, :title, :topic, :image, :user, :audiofile
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :user
  belongs_to :topic

  after_create :create_vote

  mount_uploader :image, ImageUploader
  mount_uploader :audiofile, AudiofileUploader

  delegate :username, to: :user, allow_nil: true

  default_scope order('rank ASC')

  scope :visible_to, lambda { |user| user ? scoped : joins(:topic).where('topics.public' => true) }
  scope :in_last_week, where('created_at < ?', 1.week.ago)

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :topic, presence: true
  validates :user, presence: true

  def date_added
    created_at.strftime('%d %B, %Y')
  end

  def up_votes
    votes.where(value: 1).count
  end
  
  def down_votes
    votes.where(value: -1).count
  end

  def increment_view_count
    count = self.view_count
    update_attribute(:view_count, count.succ)
    update_rank
  end

  def points
    votes.sum(:value).to_i
  end

  def update_rank
    age = (self.created_at - Time.at(0)) / 86400
    new_rank = points + age + view_count + comments.count
    update_attribute(:rank, new_rank)
  end

  def time_remaining
    (Date.today - self.created_at.to_date).to_i
  end

  def save_with_initial_vote
    ActiveRecord::Base.transaction do
      save!
      create_vote
    end
  end
  
  private

  def create_vote
    user.votes.create(value: 1, post: self)
  end
  
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  include Paginate
  attr_accessible :description, :name, :public
  has_many :posts, dependent: :destroy

  default_scope order('created_at DESC')

  scope :visible_to, lambda { |user| user ? scoped : where(public: true) }

end

app/controllers/topics/posts_controller.rb
class Topics::PostsController < ApplicationController
  
  before_filter :ensure_post, except: [:new, :create]
  before_filter :ensure_topic
  before_filter :authenticate_user!
  after_filter :update_view_count, only: [:show]

  def show
    authorize! :read, @topic, message: 'You need to be signed in to do that'
    @comment = current_user.comments.build
    @comments = @post.comments
  end

  def new
    @post = Post.new
    authorize! :create, Post, message: 'You need to be a member to create a post'
  end

  def create
    @post = current_user.posts.build(params[:post])
    @post.topic = @topic
    authorize! :create, @post, message: 'You need to be signed up to do that'
    if @post.save_with_initial_vote
      redirect_to [@topic, @post], notice: 'Post saved'
    else
      render :new, alert: 'There was an error saving your post.  Please try again.'
    end
  end

  def edit
    render
    authorize! :edit, @post, message: 'You need to own the post to edit it'
  end

  def update
    authorize! :update, @post, message: 'You ned to own the post to edit it'
    if @post.update_attributes(params[:post])
      redirect_to [@topic, @post], notice: 'Post updated'
    else
      render :edit, alert: 'Post not updated; try again'
    end
  end

  def destroy
    title = @post.title
    authorize! :destroy, @post, message: 'You need to own the post to delete it'
    if @post.destroy
      redirect_to @topic, notice: "\"#{title}\" was deleted successfully"
    else
      render :show, error: 'There was an error deleting the post'
    end
  end

  private

  def update_view_count
    @post.increment_view_count
  end

  def ensure_post
    redirect_to topics_path, alert: 'No such post' unless post
  end

  def post
    @post ||= Post.find_by_id(params[:id])
  end

  def ensure_topic
    redirect_to topics_path, alert: 'No such topic' unless topic
  end

  def topic
    @topic ||= Topic.find_by_id(params[:topic_id])
  end
  
  helper_method :post
  helper_method :topic
  
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :ensure_topic, only: [:show, :edit, :update, :destroy]

  def index
    #@topics = Topic.visible_to(current_user).paginate(page: params[:page], per_page: 5)
    @topics = Topic.paginate(page: params[:page], per_page: 10)
  end

  def new
    @topic = Topic.new
    authorize! :create, @topic, message: 'You must be admin to do that'
  end

  def create
    @topic =Topic.new(params[:topic])
    authorize! :create, @topic, message: 'You must be admin to do that'
    if @topic.save
      redirect_to @topic, notice: 'Topic created'
    else
      render :new, alert: 'Topic creation failed; please try again'
    end
  end

  def update
    authorize! :update, @topic, message: 'You need to own the topic to update it'
    if @topic.update_attributes(params[:topic])
      redirect_to @topic
    else
      flash[:error] = "Error saving topic. Please try again"
      render :edit
    end
  end

  def show
    @posts = @topic.posts.includes(:user).paginate(page: params[:page], per_page: 5)
  end

  def edit
    authorize! :update, @topic, message: 'You must be admin to do that'
  end

  def destroy
    name = @topic.name
    authorize! :destroy, @topic, message: 'You need to be admin to do that'
    if @topic.destroy
      # redirect_to topics_path, notice: "#{name} was deleted successfully"
      redirect_to topics_path, notice: "Topic was deleted successfully"
    else
      render :show, error: 'There was an error deleting this topic'
    end
  end
  

  private

  def ensure_topic
    redirect_to root_path, notice: 'No such topic' unless topic
  end

  def topic
    @topic ||= Topic.find_by_id(params[:id])
  end
  
  helper_method :topic
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/posts/_form.html.haml
= form_for [@topic, @post], html: {'data-abide' => ''} do |f|
  %div 
    = f.label :title
    %br/ 
    = f.text_field :title, class: 'medium-text-field', required: true
    %small.error Title can't be blank
  %div 
    = f.label :body
    %br/ 
    = f.text_area :body, size: '30x10', class: 'medium-text-box', required: true
    %small.error Body can't be blank
  %div 
    =f.label :image
    %br/ 
    = f.file_field :image, class: 'small radius secondary button'
    /= f.hidden_field :image_cache
  %div 
    =f.label :audiofile
    %br/ 
    = f.file_field :audiofile, class: 'small radius secondary button'
  %div
    = f.submit 'Save', class: 'medium radius secondary button'

app/views/topics/posts/edit.html.haml
%h1 Edit post
.row
  .large-4.columns
    %p Guidelines for new posts
    %ul 
      %li Make sure content is appropriate
      %li Blah blah blah
      %li Yakety smakety
      %li Etc, etc, etc.
  .large-8.columns
    = render 'form'
    = link_to 'Cancel', :back, class: 'medium radius alert button'
 

app/views/topics/posts/new.html.haml
%h1 New post
.row
  .large-4.columns
    %p Guidelines for new posts
    %ul 
      %li Make sure content is appropriate
      %li Blah blah blah
      %li Yakety smakety
      %li Etc, etc, etc.
  .large-8.columns
    = render 'form'

app/views/topics/posts/show.html.haml
= link_to 'Return to topic...', topic_path(@topic)
.row
  .small-11.small-centered.columns
    = div_for(@post) do
      %h3= markdown @post.title
      %p
        = show_user_avatar(@post.user, '80x80')
        = "Posted by #{@post.username}"

      %p
        = show_post_image(@post)
      %p
        Attached audio:
      %p
        %audio{:src => "#{@post.audiofile.url}", height: '480', width: '720', controls: ''} 
        = markdown @post.body
      - if can? :edit, @post
        = link_to 'Edit Post', edit_topic_post_path(@topic, @post), class: 'tiny radius button'
      - if can? :destroy, @post
        = link_to 'Delete Post', [@topic, @post], method: :delete, class: 'tiny radius alert button', confirm: 'Are you sure you want to delete this post?'
      %section.votes 
        = render partial: 'votes/voter', locals: { topic: @topic, post: @post }
        %h3= pluralize(@post.points, 'point')
        %small 
          = pluralize(@post.up_votes, 'up vote')
          |
          = pluralize(@post.down_votes, 'down vote')
        = render partial: 'favorites/favorite', locals: { topic: @topic, post: @post }
    %h4.comments-count=  "#{@comments.count} Comments"
    .comments
      = render partial: 'comments/comment', collection: @comments

    = link_to 'Add Comment', '', id: 'reveal-comment'
    #new-comment.hide
      = render partial: 'comments/form', locals: { post: @post, comment: @comment }