config/routes.rb
Bloccit::Application.routes.draw do

  get 'about', to: 'welcome#about'

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: [:show, :index]

  resources :topics do
    resources :posts, except: [:index], controller: 'topics/posts' do
      resources :favorites, only: [:create, :destroy]
      get '/up-vote', to: 'votes#up_vote', as: :up_vote
      get '/down-vote', to: 'votes#down_vote', as: :down_vote
    end
  end

  resource :dashboard, only: [:show]

  authenticated :user do
    root to: 'dashboards#show' 
  end

  root to: 'welcome#index'
 
end

app/models/dashboard.rb
class Dashboard

  def initialize user
    @user = user
  end

  attr_reader :user

  def username
    user.username
  end

end
  

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @dashboard = Dashboard.new(current_user)
    @posts = Post.visible_to(current_user).
      in_last_week.
      paginate(page: params[:page], per_page: 5).
      includes(:topic)
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/show.html.haml
%h1 Welcome to your dashboard

%p
  You are signed in as
  = @dashboard.username

%p Upload a random audio file.  Because you can.

%p
  View all
  = link_to 'topics', topics_path
%p 
  = link_to "Top users", users_path

%h3 Popular posts today:
= render partial: 'posts/post', collection: @posts
= will_paginate @posts, renderer: FoundationPagination::Rails